alter table public.checkout_sessions alter column status type text using status::text;
drop type public.checkout_status;
alter table public.checkout_sessions add constraint checkout_status_check check(status in('IN_PROGRESS','READY','COMPLETED','EXPIRED','CANCELED'));
alter table public.checkout_sessions add constraint checkout_sessions_location_id_id_key unique(location_id,id);

create type public.order_status as enum('CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELED');
create table public.order_number_counters(location_id uuid primary key references public.locations(id) on delete cascade,next_number bigint not null check(next_number>0));
create table public.orders(
 id uuid primary key default gen_random_uuid(),location_id uuid not null references public.locations(id),checkout_id uuid not null unique,display_number bigint not null check(display_number>0),status public.order_status not null default 'CONFIRMED',revision integer not null default 0 check(revision>=0),fulfillment_type public.fulfillment_type not null,
 customer_name text not null,customer_phone text not null,delivery_address_snapshot jsonb,subtotal numeric(12,2) not null check(subtotal>=0),delivery_fee numeric(12,2) not null check(delivery_fee>=0),total numeric(12,2) not null check(total=subtotal+delivery_fee),scheduled_for timestamptz,
 created_at timestamptz not null default now(),confirmed_at timestamptz not null default now(),ready_at timestamptz,delivered_at timestamptz,canceled_at timestamptz,cancel_reason text,
 unique(location_id,id),unique(location_id,display_number),foreign key(location_id,checkout_id) references public.checkout_sessions(location_id,id)
);
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id) on delete set null,product_name_snapshot text not null,variant_id uuid references public.product_variants(id) on delete set null,variant_name_snapshot text,unit_price numeric(12,2) not null check(unit_price>=0),quantity integer not null check(quantity between 1 and 99),line_total numeric(12,2) not null check(line_total=unit_price*quantity));
create table public.order_item_modifiers(id uuid primary key default gen_random_uuid(),order_item_id uuid not null references public.order_items(id) on delete cascade,modifier_group_id uuid references public.modifier_groups(id) on delete set null,modifier_group_name_snapshot text not null,modifier_option_id uuid references public.modifier_options(id) on delete set null,modifier_option_name_snapshot text not null,price_delta numeric(12,2) not null,unique(order_item_id,modifier_option_id));
create table public.order_status_history(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,from_status public.order_status,to_status public.order_status not null,event_type text not null check(event_type in('ORDER_CREATED','ORDER_STATUS_CHANGED','ORDER_CANCELED','ORDER_DELIVERED')),actor_type text not null check(actor_type in('CUSTOMER','STAFF','SYSTEM')),actor_id uuid,reason text,created_at timestamptz not null default now());
create index orders_location_created_idx on public.orders(location_id,created_at desc);create index order_items_order_idx on public.order_items(order_id);create index order_history_order_idx on public.order_status_history(order_id,created_at);
alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.order_item_modifiers enable row level security;alter table public.order_status_history enable row level security;alter table public.order_number_counters enable row level security;

create function private.can_order(target_location_id uuid,required_permission text) returns boolean language sql stable security definer set search_path='' as $$select public.can_access_location(target_location_id) and public.has_permission((select organization_id from public.locations where id=target_location_id),required_permission)$$;
revoke all on function private.can_order(uuid,text) from public;grant execute on function private.can_order(uuid,text) to authenticated;
create policy orders_read on public.orders for select to authenticated using(private.can_order(location_id,'orders.read'));
create policy order_items_read on public.order_items for select to authenticated using(private.can_order((select location_id from public.orders where id=order_id),'orders.read'));
create policy order_modifiers_read on public.order_item_modifiers for select to authenticated using(private.can_order((select o.location_id from public.order_items i join public.orders o on o.id=i.order_id where i.id=order_item_id),'orders.read'));
create policy order_history_read on public.order_status_history for select to authenticated using(private.can_order((select location_id from public.orders where id=order_id),'orders.read'));
grant select on public.orders,public.order_items,public.order_item_modifiers,public.order_status_history to authenticated;

create function private.order_json(target_order_id uuid,include_private boolean default false) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('id',case when include_private then o.id end,'displayNumber',lpad(o.display_number::text,4,'0'),'status',o.status,'revision',case when include_private then o.revision end,'fulfillmentType',o.fulfillment_type,'customer',case when include_private then jsonb_build_object('name',o.customer_name,'phone',o.customer_phone) end,'address',case when include_private then o.delivery_address_snapshot end,'subtotal',o.subtotal::text,'deliveryFee',o.delivery_fee::text,'total',o.total::text,'createdAt',o.created_at,'items',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'name',i.product_name_snapshot,'variant',i.variant_name_snapshot,'unitPrice',i.unit_price::text,'quantity',i.quantity,'lineTotal',i.line_total::text,'modifiers',coalesce((select jsonb_agg(jsonb_build_object('group',m.modifier_group_name_snapshot,'name',m.modifier_option_name_snapshot,'priceDelta',m.price_delta::text)) from public.order_item_modifiers m where m.order_item_id=i.id),'[]'::jsonb)) order by i.id) from public.order_items i where i.order_id=o.id),'[]'::jsonb),'timeline',case when include_private then coalesce((select jsonb_agg(jsonb_build_object('from',h.from_status,'to',h.to_status,'eventType',h.event_type,'createdAt',h.created_at,'reason',h.reason) order by h.created_at) from public.order_status_history h where h.order_id=o.id),'[]'::jsonb) end) from public.orders o where o.id=target_order_id$$;
revoke all on function private.order_json(uuid,boolean) from public;

create function public.create_order_from_checkout(cart_token text,target_idempotency_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare x public.checkout_sessions;c public.carts;o public.orders;number bigint;item record;new_item uuid;calculated numeric(12,2);begin
 select x0.* into x from public.checkout_sessions x0 join public.carts c0 on c0.id=x0.cart_id where c0.public_token_hash=encode(extensions.digest(cart_token,'sha256'),'hex') for update of x0;if x.id is null then raise exception 'ORDER_NOT_FOUND';end if;
 select * into o from public.orders where checkout_id=x.id;if o.id is not null then return private.order_json(o.id,false);end if;
 select * into c from public.carts where id=x.cart_id for update;if x.status<>'READY' then raise exception 'CHECKOUT_NOT_READY';end if;if x.expires_at<=now() then raise exception 'CHECKOUT_NOT_READY';end if;if c.status<>'ACTIVE' or x.cart_revision_validated is distinct from c.revision then raise exception 'CHECKOUT_STALE';end if;
 select coalesce(sum(line_total),0) into calculated from public.cart_items where cart_id=c.id;if calculated<>x.subtotal or x.total<>x.subtotal+x.delivery_fee then raise exception 'CHECKOUT_STALE';end if;
 insert into public.order_number_counters(location_id,next_number) values(x.location_id,2) on conflict(location_id) do update set next_number=public.order_number_counters.next_number+1 returning next_number-1 into number;
 insert into public.orders(location_id,checkout_id,display_number,fulfillment_type,customer_name,customer_phone,delivery_address_snapshot,subtotal,delivery_fee,total,scheduled_for) values(x.location_id,x.id,number,x.fulfillment_type,x.customer_name,x.customer_phone,case when x.fulfillment_type='DELIVERY' then jsonb_build_object('postalCode',x.postal_code,'street',x.street,'number',x.address_number,'complement',x.complement,'neighborhood',x.neighborhood,'city',x.city,'state',x.state,'reference',x.reference) end,x.subtotal,x.delivery_fee,x.total,x.scheduled_for) returning * into o;
 for item in select * from public.cart_items where cart_id=c.id loop new_item:=extensions.gen_random_uuid();insert into public.order_items(id,order_id,product_id,product_name_snapshot,variant_id,variant_name_snapshot,unit_price,quantity,line_total) values(new_item,o.id,item.product_id,item.product_name_snapshot,item.variant_id,item.variant_name_snapshot,item.unit_price_snapshot,item.quantity,item.line_total);insert into public.order_item_modifiers(order_item_id,modifier_group_id,modifier_group_name_snapshot,modifier_option_id,modifier_option_name_snapshot,price_delta) select new_item,m.modifier_group_id,g.name,m.modifier_option_id,m.option_name_snapshot,m.price_delta_snapshot from public.cart_item_modifiers m join public.modifier_groups g on g.id=m.modifier_group_id where m.cart_item_id=item.id;end loop;
 insert into public.order_status_history(order_id,to_status,event_type,actor_type) values(o.id,'CONFIRMED','ORDER_CREATED','CUSTOMER');update public.checkout_sessions set status='COMPLETED',updated_at=now() where id=x.id;update public.carts set status='CONVERTED',updated_at=now() where id=c.id;return private.order_json(o.id,false);end$$;
create function public.get_public_order_status(cart_token text) returns jsonb language sql stable security definer set search_path='' as $$select private.order_json(o.id,false) from public.orders o join public.checkout_sessions x on x.id=o.checkout_id join public.carts c on c.id=x.cart_id where c.public_token_hash=encode(extensions.digest(cart_token,'sha256'),'hex')$$;

create function public.list_orders(target_location_id uuid) returns jsonb language sql stable security invoker set search_path='' as $$select coalesce(jsonb_agg(private.order_json(id,true) order by created_at desc),'[]'::jsonb) from public.orders where location_id=target_location_id and private.can_order(location_id,'orders.read')$$;
create function public.update_order_status(target_order_id uuid,expected_revision integer,target_status public.order_status,target_reason text default null) returns jsonb language plpgsql security definer set search_path='' as $$declare o public.orders;event text;begin select * into o from public.orders where id=target_order_id for update;if o.id is null or not private.can_order(o.location_id,'orders.update') then raise exception 'ORDER_NOT_FOUND';end if;if o.revision<>expected_revision then raise exception 'ORDER_REVISION_CONFLICT';end if;if o.status='CANCELED' then raise exception 'ORDER_ALREADY_CANCELED';end if;if o.status='DELIVERED' then raise exception 'ORDER_ALREADY_DELIVERED';end if;if not((o.status='CONFIRMED' and target_status in('PREPARING','CANCELED'))or(o.status='PREPARING' and target_status in('READY','CANCELED'))or(o.status='READY' and target_status in('OUT_FOR_DELIVERY','DELIVERED','CANCELED') and not(o.fulfillment_type='PICKUP' and target_status='OUT_FOR_DELIVERY'))or(o.status='OUT_FOR_DELIVERY' and target_status in('DELIVERED','CANCELED')))then raise exception 'INVALID_ORDER_TRANSITION';end if;event:=case when target_status='CANCELED' then 'ORDER_CANCELED' when target_status='DELIVERED' then 'ORDER_DELIVERED' else 'ORDER_STATUS_CHANGED' end;update public.orders set status=target_status,revision=revision+1,ready_at=case when target_status='READY' then now() else ready_at end,delivered_at=case when target_status='DELIVERED' then now() else delivered_at end,canceled_at=case when target_status='CANCELED' then now() else canceled_at end,cancel_reason=case when target_status='CANCELED' then nullif(btrim(target_reason),'') else cancel_reason end where id=o.id;insert into public.order_status_history(order_id,from_status,to_status,event_type,actor_type,actor_id,reason)values(o.id,o.status,target_status,event,'STAFF',auth.uid(),target_reason);return private.order_json(o.id,true);end$$;

revoke all on function public.create_order_from_checkout(text,uuid),public.get_public_order_status(text),public.list_orders(uuid),public.update_order_status(uuid,integer,public.order_status,text) from public;
grant execute on function public.create_order_from_checkout(text,uuid),public.get_public_order_status(text) to anon,authenticated;grant execute on function public.list_orders(uuid),public.update_order_status(uuid,integer,public.order_status,text) to authenticated;
