create type public.cart_status as enum('ACTIVE','CONVERTED','ABANDONED','EXPIRED');
create table public.carts(id uuid primary key default gen_random_uuid(),location_id uuid not null references public.locations(id),status public.cart_status not null default 'ACTIVE',revision integer not null default 0 check(revision>=0),public_token_hash text not null unique check(length(public_token_hash)=64),subtotal numeric(12,2) not null default 0 check(subtotal>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),expires_at timestamptz not null default(now()+interval '24 hours'),unique(location_id,id));
create table public.cart_items(id uuid primary key default gen_random_uuid(),cart_id uuid not null references public.carts(id) on delete cascade,product_id uuid not null references public.products(id),variant_id uuid references public.product_variants(id),quantity integer not null check(quantity between 1 and 99),product_name_snapshot text not null,variant_name_snapshot text,unit_price_snapshot numeric(12,2) not null check(unit_price_snapshot>=0),line_total numeric(12,2) not null check(line_total>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.cart_item_modifiers(cart_item_id uuid not null references public.cart_items(id) on delete cascade,modifier_group_id uuid not null references public.modifier_groups(id),modifier_option_id uuid not null references public.modifier_options(id),option_name_snapshot text not null,price_delta_snapshot numeric(12,2) not null,primary key(cart_item_id,modifier_option_id));
create table public.cart_commands(cart_id uuid not null references public.carts(id) on delete cascade,idempotency_key uuid not null,response jsonb not null,created_at timestamptz not null default now(),primary key(cart_id,idempotency_key));
create index cart_items_cart_idx on public.cart_items(cart_id);create index carts_expiry_idx on public.carts(status,expires_at);
alter table public.carts enable row level security;alter table public.cart_items enable row level security;alter table public.cart_item_modifiers enable row level security;alter table public.cart_commands enable row level security;

create function private.cart_json(target_cart_id uuid) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('revision',c.revision,'status',c.status,'subtotal',c.subtotal::text,'expiresAt',c.expires_at,'items',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'productId',i.product_id,'variantId',i.variant_id,'quantity',i.quantity,'productName',i.product_name_snapshot,'variantName',i.variant_name_snapshot,'unitPrice',i.unit_price_snapshot::text,'lineTotal',i.line_total::text,'modifiers',coalesce((select jsonb_agg(jsonb_build_object('groupId',m.modifier_group_id,'optionId',m.modifier_option_id,'name',m.option_name_snapshot,'priceDelta',m.price_delta_snapshot::text)) from public.cart_item_modifiers m where m.cart_item_id=i.id),'[]'::jsonb))) order by i.created_at) from public.cart_items i where i.cart_id=c.id),'[]'::jsonb)) from public.carts c where c.id=target_cart_id$$;
revoke all on function private.cart_json(uuid) from public;

create function public.create_public_cart(location_slug text) returns jsonb language plpgsql security definer set search_path='' as $$declare loc uuid;cid uuid;token text;begin select id into loc from public.locations where slug=location_slug;if loc is null then return null;end if;token:=encode(extensions.gen_random_bytes(32),'hex');insert into public.carts(location_id,public_token_hash) values(loc,encode(extensions.digest(token,'sha256'),'hex')) returning id into cid;return jsonb_build_object('publicToken',token,'cart',private.cart_json(cid));end$$;
create function public.get_public_cart(public_token text) returns jsonb language plpgsql security definer set search_path='' as $$declare c public.carts;begin select * into c from public.carts where public_token_hash=encode(extensions.digest(public_token,'sha256'),'hex');if c.id is null then return null;end if;if c.status='ACTIVE' and c.expires_at<=now() then update public.carts set status='EXPIRED',updated_at=now() where id=c.id;end if;return private.cart_json(c.id);end$$;
create function public.get_public_product_configuration(public_token text,target_product_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare loc uuid;begin select location_id into loc from public.carts where public_token_hash=encode(digest(public_token,'sha256'),'hex') and status='ACTIVE' and expires_at>now();if loc is null then return null;end if;return(select jsonb_build_object('id',p.id,'name',p.name,'description',p.description,'imageReference',p.image_reference,'basePrice',p.base_price::text,'available',p.is_active and p.is_available,'variants',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'name',v.name,'price',v.price::text,'default',v.is_default) order by v.sort_order) from public.product_variants v where v.product_id=p.id and v.is_active),'[]'::jsonb),'modifierGroups',coalesce((select jsonb_agg(jsonb_build_object('id',g.id,'name',g.name,'minSelections',g.min_selections,'maxSelections',g.max_selections,'required',g.is_required,'options',coalesce((select jsonb_agg(jsonb_build_object('id',o.id,'name',o.name,'priceDelta',o.price_delta::text) order by o.sort_order) from public.modifier_options o where o.modifier_group_id=g.id and o.is_available),'[]'::jsonb)) order by g.sort_order) from public.modifier_groups g where g.product_id=p.id and g.is_active),'[]'::jsonb)) from public.products p where p.id=target_product_id and p.location_id=loc);end$$;
alter function public.get_public_product_configuration(text,uuid) set search_path='extensions';

create function public.mutate_public_cart(public_token text,expected_revision integer,target_idempotency_key uuid,action jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare c public.carts;cached jsonb;kind text;item_id uuid;product_id uuid;variant_id uuid;qty integer;product public.products;variant public.product_variants;unit numeric(12,2);modifier_total numeric(12,2);option_id uuid;option_record record;group_record record;selected_count integer;new_item uuid;result jsonb;begin
 select * into c from public.carts where public_token_hash=encode(extensions.digest(public_token,'sha256'),'hex') for update;if c.id is null then raise exception 'CART_NOT_FOUND';end if;
 select response into cached from public.cart_commands where cart_id=c.id and idempotency_key=target_idempotency_key;if cached is not null then return cached;end if;
 if c.expires_at<=now() then update public.carts set status='EXPIRED' where id=c.id;raise exception 'CART_EXPIRED';end if;if c.status<>'ACTIVE' then raise exception 'CART_NOT_ACTIVE';end if;if c.revision<>expected_revision then raise exception 'CART_REVISION_CONFLICT';end if;
 kind:=action->>'type';if kind='REMOVE' then item_id:=(action->>'itemId')::uuid;delete from public.cart_items where id=item_id and cart_id=c.id;if not found then raise exception 'CART_NOT_FOUND';end if;
 else
  product_id:=(action->>'productId')::uuid;qty:=(action->>'quantity')::integer;if qty<1 or qty>99 then raise exception 'INVALID_QUANTITY';end if;
  select * into product from public.products where id=product_id and location_id=c.location_id;if product.id is null then raise exception 'CROSS_LOCATION_REFERENCE';end if;if not product.is_active or not product.is_available then raise exception 'PRODUCT_NOT_AVAILABLE';end if;
  variant_id:=nullif(action->>'variantId','')::uuid;unit:=product.base_price;
  if exists(select 1 from public.product_variants where product_id=product.id and is_active) then if variant_id is null then select * into variant from public.product_variants where product_id=product.id and is_active and is_default;else select * into variant from public.product_variants where id=variant_id and product_id=product.id and is_active;end if;if variant.id is null then raise exception 'INVALID_VARIANT';end if;unit:=variant.price;elsif variant_id is not null then raise exception 'INVALID_VARIANT';end if;
  for group_record in select * from public.modifier_groups where product_id=product.id and is_active loop select count(*) into selected_count from jsonb_array_elements_text(coalesce(action->'modifierOptionIds','[]')) x join public.modifier_options o on o.id=x.value::uuid where o.modifier_group_id=group_record.id and o.is_available;if selected_count<group_record.min_selections then raise exception 'MODIFIER_MIN_NOT_MET';end if;if selected_count>group_record.max_selections then raise exception 'MODIFIER_MAX_EXCEEDED';end if;end loop;
  if (select count(*) from jsonb_array_elements_text(coalesce(action->'modifierOptionIds','[]')))<>(select count(distinct value) from jsonb_array_elements_text(coalesce(action->'modifierOptionIds','[]'))) then raise exception 'INVALID_MODIFIER_OPTION';end if;
  if (select count(*) from jsonb_array_elements_text(coalesce(action->'modifierOptionIds','[]')))<>(select count(*) from jsonb_array_elements_text(coalesce(action->'modifierOptionIds','[]')) x join public.modifier_options o on o.id=x.value::uuid join public.modifier_groups g on g.id=o.modifier_group_id where g.product_id=product.id and g.is_active and o.is_available) then raise exception 'INVALID_MODIFIER_OPTION';end if;
  select coalesce(sum(o.price_delta),0) into modifier_total from jsonb_array_elements_text(coalesce(action->'modifierOptionIds','[]')) x join public.modifier_options o on o.id=x.value::uuid;unit:=unit+modifier_total;if unit<0 then raise exception 'NEGATIVE_ITEM_TOTAL';end if;
  if kind='UPDATE' then item_id:=(action->>'itemId')::uuid;delete from public.cart_items where id=item_id and cart_id=c.id;if not found then raise exception 'CART_NOT_FOUND';end if;new_item:=item_id;else new_item:=extensions.gen_random_uuid();end if;
  insert into public.cart_items(id,cart_id,product_id,variant_id,quantity,product_name_snapshot,variant_name_snapshot,unit_price_snapshot,line_total) values(new_item,c.id,product.id,variant.id,qty,product.name,variant.name,unit,unit*qty);
  for option_id in select value::uuid from jsonb_array_elements_text(coalesce(action->'modifierOptionIds','[]')) loop select o.*,g.id group_id into option_record from public.modifier_options o join public.modifier_groups g on g.id=o.modifier_group_id where o.id=option_id;insert into public.cart_item_modifiers values(new_item,option_record.group_id,option_record.id,option_record.name,option_record.price_delta);end loop;
 end if;
 update public.carts set subtotal=coalesce((select sum(line_total) from public.cart_items where cart_id=c.id),0),revision=revision+1,updated_at=now(),expires_at=now()+interval '24 hours' where id=c.id;result:=private.cart_json(c.id);insert into public.cart_commands values(c.id,target_idempotency_key,result);return result;end$$;

revoke all on function public.create_public_cart(text),public.get_public_cart(text),public.get_public_product_configuration(text,uuid),public.mutate_public_cart(text,integer,uuid,jsonb) from public;
grant execute on function public.create_public_cart(text),public.get_public_cart(text),public.get_public_product_configuration(text,uuid),public.mutate_public_cart(text,integer,uuid,jsonb) to anon,authenticated;
